name: Update Browserslist DB

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: oven-sh/setup-bun@v1
        name: Setup Bun
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: 20

      - run: npx update-browserslist-db@latest
        name: Update browserslist-db

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit and push changes
        with:
          commit_message: "Automated update of browserslist-db"
          push_options: '--force'
          github_token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}  # Use the secret here
