name: Update Browserslist DB

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}  # Ensure only one run per branch
  cancel-in-progress: true  # Cancel any in-progress jobs

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        name: Setup Bun
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: 20

      - run: npx update-browserslist-db@latest
        name: Update browserslist-db

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://CoachJ87:${{ secrets.ACTIONS_ACCESS_TOKEN }}@github.com/CoachJ87/website-murder-mystery-party-generator.git  # Set remote URL with PAT
          git add .
          git commit -m "Automated update of browserslist-db"
          git push origin main --force
        name: Commit and push changes (Direct Git with PAT)
